import { Circle,CircleMarker,MapContainer,Marker,Polyline,TileLayer,Tooltip,useMap,useMapEvents } from 'react-leaflet';
import L from 'leaflet';
import { useEffect,useRef,useState } from 'react';
import { romePOIs } from '../../data/rome-pois';
import { guatemalaCityPOIs,zacapaPOIs } from '../../data/guatemala-pois';
import { zacapaExtraPOIs } from '../../data/zacapa-extra-pois';
import { romeExpansionPOIs,guatemalaExpansionPOIs,zacapaExpansionPOIs } from '../../data/expansion-pois';
import type { UserPosition } from '../../hooks/useGeolocation';
import type { POI } from '../../types/poi';
type Demo='rome'|'guatemala'|'zacapa';
const CENTERS:Record<Demo,{center:[number,number],zoom:number}>={rome:{center:[41.8986,12.4769],zoom:14},guatemala:{center:[14.6418,-90.5137],zoom:13},zacapa:{center:[14.985,-89.55],zoom:12}};
const icon=(p:POI)=>L.divIcon({className:'poi-marker poi-marker--compact',html:'<span aria-hidden="true">'+p.emoji+'</span><span class="sr-only">'+p.name+'</span>',iconSize:[30,30],iconAnchor:[15,15]});
function Motion({position,demo,demoFocusKey,focusedPOI}:{position:UserPosition|null;demo:Demo;demoFocusKey:number;focusedPOI:POI|null}){const map=useMap();const gps=useRef(false);useEffect(()=>{if(position&&demoFocusKey===0&&!gps.current){gps.current=true;map.flyTo([position.lat,position.lng],Math.max(map.getZoom(),15),{duration:1.2})}},[position,map,demoFocusKey]);useEffect(()=>{if(demoFocusKey>0){const d=CENTERS[demo];map.flyTo(d.center,d.zoom,{duration:1.2})}},[demo,demoFocusKey,map]);useEffect(()=>{if(focusedPOI)map.flyTo([focusedPOI.lat,focusedPOI.lng],16,{duration:.8})},[focusedPOI,map]);return null}
function TileStatus({setLoading}:{setLoading:(v:boolean)=>void}){useMapEvents({movestart:()=>setLoading(true),moveend:()=>setLoading(false),zoomstart:()=>setLoading(true),zoomend:()=>setLoading(false)});return null}
export function TravelMap({position,onSelectPOI,demo,demoFocusKey,focusedPOI,filteredPOIs,activeTour=[],darkMode=false}:{position:UserPosition|null;onSelectPOI:(p:POI)=>void;demo:Demo;demoFocusKey:number;focusedPOI:POI|null;filteredPOIs?:POI[];activeTour?:POI[];darkMode?:boolean}){const [loading,setLoading]=useState(false);const defaults=demo==='guatemala'?[...guatemalaCityPOIs,...guatemalaExpansionPOIs]:demo==='zacapa'?[...zacapaPOIs,...zacapaExtraPOIs,...zacapaExpansionPOIs]:[...romePOIs,...romeExpansionPOIs];const pois=filteredPOIs??defaults;return <><MapContainer center={CENTERS.rome.center} zoom={14} zoomControl={false} attributionControl className={'travel-map '+(darkMode?'map-dark':'')}><TileLayer keepBuffer={4} attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{activeTour.length>1&&<Polyline positions={activeTour.map(p=>[p.lat,p.lng] as [number,number])} pathOptions={{weight:5,opacity:.8,dashArray:'10 7'}}/>}{pois.map(p=><Marker key={p.id} position={[p.lat,p.lng]} icon={icon(p)} title={p.name} alt={p.name} eventHandlers={{click:()=>onSelectPOI(p)}}><Tooltip direction="bottom" offset={[0,12]} permanent={false}>{p.name}</Tooltip></Marker>)}{position&&<><Circle center={[position.lat,position.lng]} radius={position.accuracy}/><CircleMarker center={[position.lat,position.lng]} radius={8}/></>}<Motion position={position} demo={demo} demoFocusKey={demoFocusKey} focusedPOI={focusedPOI}/><TileStatus setLoading={setLoading}/></MapContainer>{loading&&<div className="map-loading" aria-label="Loading map"><span/></div>}</>}
